version: '2'
services:
  moviebot:
    container_name: "moviebot"
    build: .
    depends_on: 
      - database
  database:
    image: 'mongo:4.2.8'
    container_name: "database"
    command: [--auth]
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - ./../moviebot-data:/data/db
    ports:
      - "$MONGO_PORT:27017"
