version: '2'
services:
  moviebot:
    container_name: "moviebot"
    build: .
    depends_on: 
      - database
  database:
    image: 'mongo:4.2.8'
    container_name: "database"
    volumes:
      - /home/docker/moviebot-data:/data/db
    ports:
      - "27017:27017"
